swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

          
          
  /{account}/transactions:
    get:
      tags:
        - Transactions Module
      summary: Monthly Transactions
      description: API for fetching user's transactions for the current month
      parameters:
        - name: account
          in: path
          description: user account
          required: true
          type: integer
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: transactions/ID Payload
          required: true
          schema:
            $ref: '#/definitions/Transactions'
      produces:
        - application/json
      responses:
        '200':
          description: User's transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /{account}/transaction/{ID}:
    get:
      tags:
        - Transactions Module
      summary: TransactionID informations
      description: API for fetching user's transaction ID informations
      parameters:
        - name: account
          in: path
          description: user account
          required: true
          type: integer
        - name: ID
          in: path
          description: transactionID
          required: true
          type: string
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: transactions/ID Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionId'
    
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction ID informations retrieved successully
          schema:
            $ref: '#/definitions/TransactionIdResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: TransactionID informations
      description: API for updating user's transaction ID informations
      parameters:
        - name: account
          in: path
          description: user account
          required: true
          type: integer
        - name: ID
          in: path
          description: transactionID
          required: true
          type: string
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: transactions/ID Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionIdUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction ID informations updated successully
          schema:
            $ref: '#/definitions/TransactionIdResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error



securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
        
        
        
  Transactions:
    type: object
    properties:
      account:
        type: integer
      date:
        type: string
        format: date
        
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
              account:
                type: integer
              date:
                type: string
                format: date
              description:
                type: string
              amount: 
                type: number
              balance:
                type: number      
  
  
  TransactionId:
    type: object
    properties:
      account:
        type: integer
      transactionID:
        type: string
        
  TransactionIdUpdate:
    type: object
    properties:
      account:
        type: integer
      transactionID:
        type: string
      category:
        type: string
      notes: 
        type: string  
          
  TransactionIdResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
            account:
              type: integer
            transactionID:
              type: string
            transaction_type:
              type: string
            category:
              type: string
            notes: 
              type: string
       

